[package]
name = "arrakis"
version = "0.0.1"
authors = ["squeakbug73 <squeakbug73@outlook.com>"]
edition = "2021"

[profile.release]
lto = true
opt-level = 2
codegen-units = 1

[lib]
name = "kernel"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
