[package]
name = "mm"
version = "0.1.0"
edition = "2021"

[dependencies]
spin.workspace = true
bitflags.workspace = true
types.workspace = true
dev.workspace = true

jemallocator = { version = "0.5.4" , optional = true }

[features]
with_std = [ "jemallocator" ]
