[package]
name = "dev"
version = "0.0.1"
authors = ["squeakbug <squeakbug73@outlook.com>"]
edition = "2021"

[dependencies]
spin.workspace = true

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
